#!/bin/bash -ex
# required environment variables: CODENAME

fatal() {
    echo "[$(basename $0)] fatal: $@" 1>&2
    exit 1
}


NAME="wheezy-backports"
PACKAGES="redis-server"

[ "$CODENAME" == "wheezy" ] || fatal "CODENAME is not wheezy, it is $CODENAME"

cat >/etc/apt/sources.list.d/$NAME.list<<EOF
deb http://ftp.debian.org/debian $NAME main
EOF

cat >/etc/apt/preferences.d/$NAME<<EOF
Package: *
Pin: release a=$NAME
Pin-Priority: 100

Package: $PACKAGES
Pin: release a=$NAME
Pin-Priority: 500
EOF

apt-get update
DEBIAN_FRONTEND=noninteractive apt-get --force-yes --assume-yes install $PACKAGES

