#!/bin/bash -ex

source /usr/local/src/gitlab.conf

[ "$FAB_HTTP_PROXY" ] && export HTTP_PROXY=$FAB_HTTP_PROXY

dl() {
    PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}


# install ruby from source
mkdir -p $RUBY_TMP
cd $RUBY_TMP
dl $RUBY_URL .
echo "$RUBY_SHA  $RUBY_TAR" | shasum -c - && tar xzf $RUBY_TAR
cd ${RUBY_TAR%.tar*}
./configure --disable-install-rdoc
make
make install
cd ~
rm -rf $RUBY_TMP

# install gems
gem install bundler --no-ri --no-rdoc

# install yarn
# (sources and gpg key added in overlay)
apt-get update && apt-get install yarn

# install Golang
echo "https://storage.googleapis.com/golang/go${VERSION_GO}.linux-amd64.tar.gz"
curl --remote-name --progress "https://storage.googleapis.com/golang/go${VERSION_GO}.linux-amd64.tar.gz"
echo "fa1b0e45d3b647c252f51f5e1204aba049cde4af177ef9f2181f43004f901035  go${VERSION_GO}.linux-amd64.tar.gz" | shasum -a256 -c -
tar -C /usr/local -xzf go${VERSION_GO}.linux-amd64.tar.gz
ln -sf /usr/local/go/bin/{go,godoc,gofmt} /usr/local/bin/
rm go${VERSION_GO}.linux-amd64.tar.gz

unset HTTP_PROXY
