#!/bin/bash -ex

source /usr/local/src/gitlab.conf

# install gems
[ "$FAB_HTTP_PROXY" ] && export HTTP_PROXY=$FAB_HTTP_PROXY
gem install bundler
gem install charlock_holmes --version $VERSION_CHARLOCK_HOLMES
unset HTTP_PROXY

