#!/bin/bash -ex

source /usr/local/src/gitlab.conf
[ "$FAB_HTTP_PROXY" ] && export HTTP_PROXY=$FAB_HTTP_PROXY

# install yarn
# (sources and gpg key added in overlay)
apt-get update && apt-get install yarn
unset HTTP_PROXY

