#!/bin/bash -ex

source /usr/local/src/gitlab.conf

# download
URL="https://github.com/gitlabhq/gitolite.git"

[ "$FAB_HTTP_PROXY" ] && export HTTP_PROXY=$FAB_HTTP_PROXY
exec_git "git clone -b $VERSION_GITOLITE $URL $GIT_HOME/gitolite"
unset HTTP_PROXY

# add gitolite to the users path
exec_git "mkdir -p $GIT_HOME/bin"
exec_git "$GIT_HOME/gitolite/install -ln $GIT_HOME/bin"

exec_git "cat >$GIT_HOME/.profile<<EOF
PATH=\$PATH:/$GIT_HOME/bin
export PATH
EOF"

# copy gitlab's public ssh key and use as admin key for gitolite setup
cp $GITLAB_HOME/.ssh/id_rsa.pub $GIT_HOME/gitlab.pub
chmod 0444 $GIT_HOME/gitlab.pub
exec_git "gitolite setup -pk $GIT_HOME/gitlab.pub"

# make sure the gitolite config is owned by git user
chmod 750 $GIT_HOME/.gitolite
chown -R $GIT_USER:$GIT_USER $GIT_HOME/.gitolite

# make sure the repositories dir is owned by git user (and stays that way)
chmod -R ug+rwX,o-rwx $GIT_HOME/repositories
chown -R $GIT_USER:$GIT_USER $GIT_HOME/repositories
find $GIT_HOME/repositories -type d -print0 | xargs -0 chmod g+s

## TESTING
#/etc/init.d/ssh start
#sudo -u gitlab -H git clone git@localhost:gitolite-admin.git /tmp/gitolite-admin
#rm -rf /tmp/gitolite-admin
#/etc/init.d/ssh stop

