#!/bin/bash -ex

source /usr/local/src/gitlab.conf

MYCNF=/etc/mysql/mariadb.conf.d/99-turnkey-redmine-workaround.cnf
cat > $MYCNF <<EOF
  [mysqld]
  default_tmp_storage_engine = InnoDB
  innodb_file_format = Barracuda
  innodb_file_format_max = Barracuda
  innodb_large_prefix = 1
EOF


/etc/init.d/mysql start

MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"
MYSQL_ADMIN="mysqladmin --user=root --password=$MYSQL_PASS"

# create database and user
$MYSQL_ADMIN create $DB_NAME --default-character-set=utf8;
$MYSQL_BATCH --execute "grant all privileges on $DB_NAME.* to '$DB_USER'@localhost identified by '$DB_PASS'; flush privileges;"

