#!/bin/bash -ex

source /usr/local/src/gitlab.conf

# workaround for mariadb v10.1 (Specified key was too long; max key length is 767)
MYCNF=/etc/mysql/mariadb.conf.d/99-turnkey-mariadb-workaround.cnf
cat > $MYCNF <<EOF
  [mysqld]
  default_tmp_storage_engine = InnoDB
  innodb_file_format = Barracuda
  innodb_file_format_max = Barracuda
  innodb_large_prefix = 1
  innodb_default_row_format = Dynamic
EOF


service mysql start

MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"
MYSQL_ADMIN="mysqladmin --user=root --password=$MYSQL_PASS"

# create database and user
$MYSQL_ADMIN create $DB_NAME --default-character-set=utf8;
$MYSQL_BATCH --execute "grant all privileges on $DB_NAME.* to '$DB_USER'@localhost identified by '$DB_PASS'; flush privileges;"

