#!/bin/bash -ex

source /usr/local/src/gitlab.conf

# setup unicorn and nginx
cd $GIT_HOME/gitlab/config
mv unicorn.rb.example unicorn.rb
sed -i '/gitlab.socket/ s/$/, :umask => 007/' unicorn.rb

rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/gitlab /etc/nginx/sites-enabled/gitlab

usermod -a -G git www-data

