#!/bin/bash -ex

source /usr/local/src/gitlab.conf

cd $GIT_HOME/gitlab

# compile assets
exec_git 'bundle exec rake gettext:compile RAILS_ENV=production'
exec_git 'yarn install --production --pure-lockfile'
exec_git 'bundle exec rake gitlab:assets:compile RAILS_ENV=production NODE_ENV=production'

# cleanup
rm -rf $SRC/*

