#!/bin/bash -e
# regenerate gitlab secrets

. /etc/default/inithooks

# already removed during initial build, but just in case they're being re-run.
rm -rf /etc/gitlab/gitlab-secrets.json

# As of v15.2 the TurnKey GitLab appliance installs the Omnibus package, so
# there is nothing more to do here.
#
# That is because with no secrets file, when 'gitlab-ctl reconfigure' is called
# (by 'bin/gitlab.py' inithook) the secrets are regenerated.
