#!/bin/bash -e
# regenerate gitlab secrets

. /etc/default/inithooks

CONF = /home/git/gitlab/config/secrets.yml
SECRET_KEY_BASE = $(mcookie)$(mcookie)$(mcookie)$(mcookie)
OTP_KEY_BASE = $(mcookie)$(mcookie)$(mcookie)$(mcookie)
DB_KEY = $(mcookie)$(mcookie)$(mcookie)$(mcookie)

# secrets.yml
sed -i "s|secret_key_base.*|secret_key_base: $SECRET_KEY_BASE|" $CONF
sed -i "s|otp_key_base.*|otp_key_base: $OTP_KEY_BASE|" $CONF
sed -i "s|db_key_base.*|db_key_base: $DB_KEY|" $CONF

# mysql password
PASSWORD=$(mcookie)
CONF=/home/git/gitlab/config/database.yml
sed -i "s/password:\(.*\)/password: $PASSWORD/" $CONF
$INITHOOKS_PATH/bin/mysqlconf.py --user=gitlab --pass="$PASSWORD"

