#!/bin/bash -e
# regenerate gitlab secrets

. /etc/default/inithooks

# As of v15.2 the TurnKey GitLab appliance installs the Omnibus package, so
# there is nothing to do here.
#
# That is because the secrets are removed during the initial install and when
# 'gitlab-ctl reconfigure' is called (by 'bin/gitlab.py' inithook) any missing
# secrets are regenerated.
