#!/bin/bash -e
# set gitlab admin password, email and domain to serve

. /etc/default/inithooks

fatal() { echo "$(basename "$0"): FATAL: $*" >&2; exit 1; }

# if GitLab isn't already running, start it
if ! systemctl is-active --quiet gitlab-runsvdir.service; then
    systemctl start gitlab-runsvdir.service
fi

if [[ -f "$INITHOOKS_CONF" ]]; then
    source "$INITHOOKS_CONF"
else
    echo "$(basename "$0"): Warning: $INITHOOKS_CONF not found or is not a file (expected if not preseeded" >&2
fi

"$INITHOOKS_PATH/bin/gitlab.py" --pass="$APP_PASS" --email="$APP_EMAIL" --domain="$APP_DOMAIN" \
    || fatal "$INITHOOKS_PATH/bin/gitlab.py failed"
